# Configuración de PostgreSQL en Supabase
# Se limpia la URL para usar solo el protocolo JDBC y la dirección del host
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.llbplmagwfzyuxbnhtsa
spring.datasource.password=Taller-Dos-Poli
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect